# Generated by Django 4.2.2 on 2023-06-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=150, verbose_name='заголовок'),
        ),
    ]
