# Generated by Django 4.2.2 on 2023-06-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shukik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='info',
            field=models.CharField(max_length=250, verbose_name='о себе'),
        ),
    ]
